//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tapanyagok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tapanyag
    {
        public int id { get; set; }
        public string nev { get; set; }
        public double energia { get; set; }
        public Nullable<double> feherje { get; set; }
        public Nullable<double> zsir { get; set; }
        public Nullable<double> szenhidrat { get; set; }
    }
}
